// indietrack-ui/src/components/TrackView.vue
<template>
  <div id="mapContainer" class="flex-grow-1 h-100"></div>
</template>

<script>
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import {ref} from "vue";
const API_URL = "http://localhost:8099";
// const API_URL = "";


export default {
  props:['trackId'],
  name: "TrackView",
  // data() {
  //   return {
  //     boundaries: [[51.0605034,13.6989567],[51.0759464,13.729364]],
  //     mapDiv: undefined,
  //     currentTrackPolyline: undefined,
  //   }
  // },
  async setup() {
    let boundaries = ref([[51.0605034,13.6989567],[51.0759464,13.729364]]);
    let mapDiv = ref(undefined);
    let currentTrackPolyline = ref(undefined);
    return {
      boundaries,
      mapDiv,
      currentTrackPolyline
    }
  },
  watch: {
    trackId(newTrackId) {
      this.updateTrackId(newTrackId);
    }
  },
  methods: {
    async updateTrackId(newTrackId) {
      console.log("changing trackId to " + newTrackId);
      if(newTrackId) {
        this.fetchTrackpoints(newTrackId)
        await this.fetchTrackInfo(newTrackId);
        await this.zoomMapToBoundaries();
      }
    },
    setupLeaflet: function() {
      this.mapDiv = L.map("mapContainer").setView([51.0605034,13.6989567], 13);
      L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
        maxZoom: 18
      }).addTo(this.mapDiv);
    },
    async fetchTrackInfo(trackId) {
      if(!trackId) {
        console.log("No trackId given.");
        return;
      }
      try  {
        console.log("Fetching track info for track " + trackId);
        let track = await (await fetch(`${API_URL}/track/${trackId}`)).json();
        console.log("Retrieved track info, updating boundaries.");
        this.boundaries = track.boundaries;
      } catch (e) {
        console.error(e);
      }
    },
    async fetchTrackpoints(trackId) {
      if(!trackId) {
        console.log("No trackId given.");
        return;
      }
      try {
        console.log("Fetching trackpoints for track "+ trackId);
        let trackpoints = await(await fetch(`${API_URL}/track/${trackId}/trackpoints`)).json();
        console.log("Fetched trackpoints, updating map.");
        if(this.currentTrackPolyline){
          this.currentTrackPolyline.removeFrom(this.mapDiv);
          this.currentTrackPolyline = undefined
        }
        const latLng = (trackpoints).map(this.mapToLatLng);
        this.currentTrackPolyline = L.polyline(latLng, {color: 'blue'}).addTo(this.mapDiv);
        this.currentTrackPolyline.bringToBack();

      } catch (e) {
        console.error(e)
      }
    },
    mapToLatLng(row) {
      return L.latLng(row.latitude, row.longitude)
    },
    async zoomMapToBoundaries() {
      this.mapDiv.fitBounds(this.boundaries);
    }
  },
  beforeRouteUpdate(newRoute){
    console.log("Setting boundaries")
    this.fetchTrackInfo(newRoute.params.id).then(() => this.zoomMapToBoundaries());
    this.fetchTrackpoints(newRoute.params.id)
  },
  mounted() {
    this.fetchTrackInfo(this.$route.params.id).then(this.setupLeaflet);
    this.fetchTrackpoints(this.$route.params.id)
  }
}
</script>

<style scoped>
  #mapContainer {
    width: 90vw;
    height: 50vh;
  }
</style>

// indietrack-client/src/app/trackview/trackview.component.ts
/// <reference path="leaflet.hg.d.ts"/>
/// <reference path="../../../node_modules/@types/d3/index.d.ts" />

import * as L from 'leaflet';
import {Component, Input, OnInit} from '@angular/core';
import {ActivatedRoute, Router} from "@angular/router";
import {TrackService} from "../track/track.service";
import {Track} from "../dto/Track";
import {LatLng, LatLngBounds} from "leaflet";
import {TrackPoint} from "../dto/TrackPoint";

@Component({
  selector: 'app-trackview',
  templateUrl: './trackview.component.html',
  styleUrls: ['./trackview.component.css']
})
export class TrackviewComponent implements OnInit {
  private mymap: L.Map;
  private _track: Track;
  private currentTrackPolyline: L.Polyline;
  constructor(private trackService: TrackService,
              private route: ActivatedRoute) { }

  @Input()
  set track(track: Track) {
    this._track = track;
    if(track) {
      this.getAndDrawTrack();
    }
  }

  get track(): Track {
    return this._track;
  }

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      if(params.get('trackId')) {
        this.trackService.getTrack(Number(params.get('trackId'))).subscribe(track => {this.track = track})
      }
    });
  }

  private getAndDrawTrack() {
    let currentTrack = this._track;
    this.trackService.getTrackPoints(currentTrack.id).subscribe(data => {
      console.log(data);
      if(this.mymap == undefined) {
        this.initMap(currentTrack.boundaries);
      } else {
        // this.mymap.setView([data[0].latitude, data[0].longitude], 12)
        this.mymap.flyToBounds(currentTrack.boundaries)
      }
      this.drawTrack(data, 'blue');
    })
  }

  private initMap(boundaries: LatLngBounds) {
    this.mymap = L.map('mapid');
    if(boundaries) {
      this.mymap.fitBounds(boundaries);
    }
    const osmUrl = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';
    L.tileLayer(osmUrl, {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      maxZoom: 18
    }).addTo(this.mymap);
  }

  private drawTrack(data, color) {
    if(this.currentTrackPolyline){
      this.currentTrackPolyline.removeFrom(this.mymap);
    }
    const latLng = (data).map(this.mapToLatLng);
    this.currentTrackPolyline = L.polyline(latLng, {color: color}).addTo(this.mymap);
    this.currentTrackPolyline.bringToBack()
  }

  private mapToLatLng(row : TrackPoint) : L.LatLng {
    return L.latLng(row.latitude, row.longitude)
  }

}

<div id="mapid" class="flex-grow-1 h-100"></div>
