// indietrack-ui/src/components/HeightProfile.vue
<template>
  <!--  <canvas *ngIf="lineChartData.length > 0" baseChart width="10vh" height="5vh"-->
  <!--          [datasets]="lineChartData"-->
  <!--          legend="false"-->
  <!--          chartType="line"-->
  <!--          [options]="chartOptions"-->
  <!--          [plugins]="chartPlugins"-->
  <!--          [colors]="lineChartColors"-->
  <!--  >-->
  <div>
    <canvas id="chart" width="400" height="400" ref="canv"></canvas>
  </div>
</template>

<script>
import Chart from 'chartjs'

export default {
  name: "HeightProfile",
  props: ['track'],
  data() {
    return {
      chartData: {
        type: 'bar',
        data: {
          labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
          datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)',
              'rgba(75, 192, 192, 1)',
              'rgba(153, 102, 255, 1)',
              'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
          }]
        },
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    }
  },
  mounted() {
    // const ctx = document.getElementById('chart').getContext('2d');
    const ctx = this.$refs.canv.getContext('2d');
    const chart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
          label: '# of Votes',
          data: [12, 19, 3, 5, 2, 3],
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)'
          ],
          borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
    console.log(chart);
  }
}
</script>

<style scoped>

</style>

// indietrack-client/src/app/heightprofile/heightprofile.component.ts
import {Component, Input, OnInit, Output} from '@angular/core';
import {Track} from "../dto/Track";
import {ChartDataSets, ChartOptions} from "chart.js";
import {TrackService} from "../track/track.service";
import {Color} from "ng2-charts";

@Component({
  selector: 'app-heightprofile',
  templateUrl: './heightprofile.component.html',
  styleUrls: ['./heightprofile.component.css']
})
export class HeightprofileComponent implements OnInit {

  private _track: Track;

  constructor(private trackService: TrackService) {  }

  @Input()
  set track(track: Track) {
    this._track = track;
    this.drawHeightProfile();
  }

  get track(): Track {
    return this._track;
  }

  private drawHeightProfile() {
    if(!this._track) return;
    let currentTrack = this._track;
    this.trackService.getSimplifiedTrackPoints(currentTrack.id).subscribe(data => {
      let elevationData = data.map((trackPoint) => {
          return {x: trackPoint.time,
            y: trackPoint.elevation};
        }
      )

      console.log(elevationData);
      this.lineChartData = [{
        data: elevationData,
        label: '',
        lineTension: 0.4,
        pointRadius: 0,
        borderWidth: 0,
        backgroundColor: 'rgba(0,0,0,0.3)'
      }];
    })

  }

  public lineChartData: ChartDataSets[] = [ ];
  public chartOptions: ChartOptions = {
    responsive: true,
    legend: {
      display: false
    },
    scales: {
      xAxes: [{
        type: 'time',
        display: true,
        scaleLabel: {
          display: true
        }
      }],
      yAxes: [{
        scaleLabel: {display: false},
        display: true
      }]
    }
  }

  public lineChartColors: Color[] = [
    {
      borderColor: 'rgba(0,0,0,0.3)',
      backgroundColor: 'rgba(0,0,0,0.3)',
    },
  ];

  ngOnInit(): void {
  }
}

<div class="heightprofilecontainer">
  <canvas *ngIf="lineChartData.length > 0" baseChart width="10vh" height="5vh"
          [datasets]="lineChartData"
          legend="false"
          chartType="line"
          [options]="chartOptions"
          [plugins]="chartPlugins"
          [colors]="lineChartColors"
  >
  </canvas>
</div>
